version: 2.1
orbs:
  helm: circleci/helm@0.2.3
jobs:
  test:
    docker:
      - image: circleci/golang:1.14
      - image: circleci/postgres:11
        environment:
          POSTGRES_USER: bete
          POSTGRES_DB: bete
          POSTGRES_HOST_AUTH_METHOD: "trust"
    environment:
      DATABASE_URL: postgres://bete@localhost:5432/bete?sslmode=disable
    steps:
      - checkout
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Initialise database
          command: |
            GOBIN=$PWD/bin go get -tags postgres github.com/golang-migrate/migrate/v4/cmd/migrate
            bin/migrate -path migrations -database "$DATABASE_URL" up
      - run:
          name: Run tests
          command: go test -v -cover -coverprofile=coverage.out -covermode=count ./...
  build:
    machine: true
    steps:
      - checkout
      - run: echo "export commit=$(git rev-parse --verify --short HEAD)" >> $BASH_ENV
      - run:
          name: Docker login
          command: echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com --username yi-jiayu --password-stdin
      - run:
          name: Docker build
          command: docker build -t docker.pkg.github.com/yi-jiayu/bete/bete:$commit --build-arg commit=$commit .
      - run:
          name: Docker push
          command: docker push docker.pkg.github.com/yi-jiayu/bete/bete:$commit
      - run:
          name: Create release in Sentry
          command: |
            curl -sL https://sentry.io/get-cli/ | bash
            sentry-cli releases new -p bete $commit
            sentry-cli releases set-commits --auto $commit
    environment:
      SENTRY_ORG: jiayu-yi
  deploy_staging:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - helm/install-helm-client:
          version: "v3.0.0"
      - run:
          name: Create kubeconfig file
          command: echo $BETE_STAGING_DEPLOYER_KUBECONFIG_BASE64 | base64 --decode > $KUBECONFIG
      - run: echo "export commit=$(git rev-parse --verify --short HEAD)" >> $BASH_ENV
      - run:
          name: Helm upgrade
          command: |
            helm upgrade --install --wait \
              bete deploy/charts/server \
              -n bete-staging \
              -f deploy/values/base.yaml \
              -f deploy/values/staging.yaml \
              --set image.tag="$commit"
      - run:
          name: Create deploy in Sentry
          command: |
            curl -sL https://sentry.io/get-cli/ | bash
            sentry-cli releases deploys "$commit" new -e staging
    environment:
      SENTRY_ORG: jiayu-yi
      KUBECONFIG: kubeconfig.yaml

workflows:
  version: 2
  deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
      - build:
          requires:
            - test
      - deploy_staging:
          requires:
            - build
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
