{{- range .Values.cronJobs -}}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "server.fullname" $ }}-{{ .name }}
  labels:
    {{- include "server.labels" $ | nindent 4 }}
spec:
  schedule: {{ .schedule }}
  {{- with .concurrencyPolicy }}
  concurrencyPolicy: {{ . }}
  {{- end }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .name }}
              image: {{ .repository | default $.Values.image.repository }}:{{ .tag | default $.Values.image.tag }}
              {{- with .command }}
              command:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with $.Values.envFromConfigMap }}
              envFrom:
                - configMapRef:
                    name: {{ . }}
              {{- end }}
          restartPolicy: OnFailure
...
{{- end }}
