image:
  repository: docker.pkg.github.com/yi-jiayu/bete/bete

imagePullSecrets:
  - name: docker.pkg.github.com

prometheus:
  enabled: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/whitelist-source-range: 149.154.160.0/20, 91.108.4.0/22

envFromConfigMap: bete

livenessProbe:
  enabled: true
  path: /metrics

readinessProbe:
  enabled: true
  path: /metrics

migration:
  enabled: true
  command:
    - /bete/bin/migrate
    - -path
    - /bete/migrations
    - -database
    - $(DATABASE_URL)
    - up

cronJobs:
  - name: sync-bus-stops
    schedule: "0 17 * * *"
    concurrencyPolicy: Forbid
    command:
      - /bete/bin/seed
